# Generated by Django 4.1.7 on 2023-02-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
    ]
