# Generated by Django 4.1.7 on 2023-02-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0002_alter_repository_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='text',
        ),
    ]
