# Generated by Django 4.1.7 on 2023-03-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0003_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
