# Generated by Django 4.1.7 on 2023-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0004_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='image',
            field=models.ImageField(default='default-repo-image.jpg', null=True, upload_to=''),
        ),
    ]
