# Generated by Django 4.1.7 on 2023-02-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0004_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='created',
        ),
    ]
