# Generated by Django 4.2 on 2023-04-03 19:17

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='default-repo-image.jpg', max_length=255, null=True)),
                ('num_of_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
