# Generated by Django 4.1.7 on 2023-03-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0007_likerepository_repository_num_of_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likerepository',
            options={'verbose_name_plural': 'likerepositories'},
        ),
    ]
