# Generated by Django 4.1.7 on 2023-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0008_repository_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
