# Generated by Django 4.1.7 on 2023-03-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0009_repository_updated_alter_repository_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='owner',
            new_name='user',
        ),
    ]
