# Generated by Django 4.1.7 on 2023-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0010_rename_owner_repository_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-updated', '-created'], 'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='repository',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='repository',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
