# Generated by Django 4.1.7 on 2023-03-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0011_alter_repository_options_repository_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='file',
        ),
    ]
