# Generated by Django 4.1.7 on 2023-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0012_remove_repository_avatar_remove_repository_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
