# Generated by Django 4.1.7 on 2023-03-30 16:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lithubs', '0015_alter_user_avatar_alter_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default-repo-image.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.svg', max_length=255, null=True),
        ),
    ]
